//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EventSystem_CloseUiBindRemoveWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(EventSystem.CloseUiBindRemove), typeof(EventSystem.EventBase));
		L.RegFunction("New", _CreateEventSystem_CloseUiBindRemove);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("EVENT_TYPE", get_EVENT_TYPE, set_EVENT_TYPE);
		L.RegVar("Config", get_Config, set_Config);
		L.RegVar("NeedRemove", get_NeedRemove, set_NeedRemove);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateEventSystem_CloseUiBindRemove(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 1, typeof(UIConfig));
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
				EventSystem.CloseUiBindRemove obj = new EventSystem.CloseUiBindRemove(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: EventSystem.CloseUiBindRemove.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EVENT_TYPE(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, EventSystem.CloseUiBindRemove.EVENT_TYPE);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Config(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			EventSystem.CloseUiBindRemove obj = (EventSystem.CloseUiBindRemove)o;
			UIConfig ret = obj.Config;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Config on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NeedRemove(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			EventSystem.CloseUiBindRemove obj = (EventSystem.CloseUiBindRemove)o;
			int ret = obj.NeedRemove;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index NeedRemove on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_EVENT_TYPE(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			EventSystem.CloseUiBindRemove.EVENT_TYPE = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Config(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			EventSystem.CloseUiBindRemove obj = (EventSystem.CloseUiBindRemove)o;
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			obj.Config = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Config on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_NeedRemove(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			EventSystem.CloseUiBindRemove obj = (EventSystem.CloseUiBindRemove)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.NeedRemove = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index NeedRemove on a nil value" : e.Message);
		}
	}
}

