//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MessageBoxTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(MessageBoxType));
		L.RegVar("OkCancel", get_OkCancel, null);
		L.RegVar("Ok", get_Ok, null);
		L.RegVar("No", get_No, null);
		L.RegVar("Cancel", get_Cancel, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OkCancel(IntPtr L)
	{
		ToLua.Push(L, MessageBoxType.OkCancel);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Ok(IntPtr L)
	{
		ToLua.Push(L, MessageBoxType.Ok);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_No(IntPtr L)
	{
		ToLua.Push(L, MessageBoxType.No);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Cancel(IntPtr L)
	{
		ToLua.Push(L, MessageBoxType.Cancel);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		MessageBoxType o = (MessageBoxType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

