//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIConfigWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UIConfig), typeof(System.Object));
		L.RegFunction("IncReference", IncReference);
		L.RegFunction("DecReference", DecReference);
		L.RegFunction("Visible", Visible);
		L.RegFunction("CleanReferenceCount", CleanReferenceCount);
		L.RegFunction("Reset", Reset);
		L.RegFunction("CleanupControllers", CleanupControllers);
		L.RegFunction("Init", Init);
		L.RegFunction("NewArgument", NewArgument);
		L.RegFunction("GetConfig", GetConfig);
		L.RegFunction("New", _CreateUIConfig);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("TypeUI", get_TypeUI, set_TypeUI);
		L.RegVar("Loction", get_Loction, set_Loction);
		L.RegVar("UiRecord", get_UiRecord, set_UiRecord);
		L.RegVar("SceneMapUI", get_SceneMapUI, set_SceneMapUI);
		L.RegVar("MainUI", get_MainUI, set_MainUI);
		L.RegVar("BackPackUI", get_BackPackUI, set_BackPackUI);
		L.RegVar("AttriFrameUI", get_AttriFrameUI, set_AttriFrameUI);
		L.RegVar("SelectEquipsUI", get_SelectEquipsUI, set_SelectEquipsUI);
		L.RegVar("SelectRoleUI", get_SelectRoleUI, set_SelectRoleUI);
		L.RegVar("BlockLayer", get_BlockLayer, set_BlockLayer);
		L.RegVar("SkillFrameUI", get_SkillFrameUI, set_SkillFrameUI);
		L.RegVar("SkillTipFrameUI", get_SkillTipFrameUI, set_SkillTipFrameUI);
		L.RegVar("MissionFrame", get_MissionFrame, set_MissionFrame);
		L.RegVar("DialogFrame", get_DialogFrame, set_DialogFrame);
		L.RegVar("TeamFrame", get_TeamFrame, set_TeamFrame);
		L.RegVar("MissionList", get_MissionList, set_MissionList);
		L.RegVar("MissionTrackList", get_MissionTrackList, set_MissionTrackList);
		L.RegVar("OperationList", get_OperationList, set_OperationList);
		L.RegVar("MessageBox", get_MessageBox, set_MessageBox);
		L.RegVar("RewardFrame", get_RewardFrame, set_RewardFrame);
		L.RegVar("EquipUI", get_EquipUI, set_EquipUI);
		L.RegVar("AchievementFrame", get_AchievementFrame, set_AchievementFrame);
		L.RegVar("ChatMainFrame", get_ChatMainFrame, set_ChatMainFrame);
		L.RegVar("AchievementTip", get_AchievementTip, set_AchievementTip);
		L.RegVar("HandBook", get_HandBook, set_HandBook);
		L.RegVar("FriendUI", get_FriendUI, set_FriendUI);
		L.RegVar("DungeonUI", get_DungeonUI, set_DungeonUI);
		L.RegVar("ComposeUI", get_ComposeUI, set_ComposeUI);
		L.RegVar("AttributeUI", get_AttributeUI, set_AttributeUI);
		L.RegVar("SettingUI", get_SettingUI, set_SettingUI);
		L.RegVar("RankUI", get_RankUI, set_RankUI);
		L.RegVar("PlayerInfoUI", get_PlayerInfoUI, set_PlayerInfoUI);
		L.RegVar("MailUI", get_MailUI, set_MailUI);
		L.RegVar("CharacterUI", get_CharacterUI, set_CharacterUI);
		L.RegVar("DepotUI", get_DepotUI, set_DepotUI);
		L.RegVar("StoreUI", get_StoreUI, set_StoreUI);
		L.RegVar("StoreEquip", get_StoreEquip, set_StoreEquip);
		L.RegVar("StoreFarm", get_StoreFarm, set_StoreFarm);
		L.RegVar("ElfUI", get_ElfUI, set_ElfUI);
		L.RegVar("WingUI", get_WingUI, set_WingUI);
		L.RegVar("SailingUI", get_SailingUI, set_SailingUI);
		L.RegVar("FarmUI", get_FarmUI, set_FarmUI);
		L.RegVar("ServerListUI", get_ServerListUI, set_ServerListUI);
		L.RegVar("MedalInfoUI", get_MedalInfoUI, set_MedalInfoUI);
		L.RegVar("AreanaUI", get_AreanaUI, set_AreanaUI);
		L.RegVar("AreanaResult", get_AreanaResult, set_AreanaResult);
		L.RegVar("ReliveUI", get_ReliveUI, set_ReliveUI);
		L.RegVar("WishingUI", get_WishingUI, set_WishingUI);
		L.RegVar("SmithyUI", get_SmithyUI, set_SmithyUI);
		L.RegVar("TradingUI", get_TradingUI, set_TradingUI);
		L.RegVar("DungeonResult", get_DungeonResult, set_DungeonResult);
		L.RegVar("RecycleUI", get_RecycleUI, set_RecycleUI);
		L.RegVar("BattleUnionUI", get_BattleUnionUI, set_BattleUnionUI);
		L.RegVar("ForceUI", get_ForceUI, set_ForceUI);
		L.RegVar("ItemInfoUI", get_ItemInfoUI, set_ItemInfoUI);
		L.RegVar("EquipComPareUI", get_EquipComPareUI, set_EquipComPareUI);
		L.RegVar("EquipInfoUI", get_EquipInfoUI, set_EquipInfoUI);
		L.RegVar("GainItemHintUI", get_GainItemHintUI, set_GainItemHintUI);
		L.RegVar("ElfInfoUI", get_ElfInfoUI, set_ElfInfoUI);
		L.RegVar("BattleUI", get_BattleUI, set_BattleUI);
		L.RegVar("BattleResult", get_BattleResult, set_BattleResult);
		L.RegVar("AstrologyUI", get_AstrologyUI, set_AstrologyUI);
		L.RegVar("NewbieGuide", get_NewbieGuide, set_NewbieGuide);
		L.RegVar("ActivityUI", get_ActivityUI, set_ActivityUI);
		L.RegVar("ActivityRewardFrame", get_ActivityRewardFrame, set_ActivityRewardFrame);
		L.RegVar("BossRewardFrame", get_BossRewardFrame, set_BossRewardFrame);
		L.RegVar("RebornUi", get_RebornUi, set_RebornUi);
		L.RegVar("OffLineExpFrame", get_OffLineExpFrame, set_OffLineExpFrame);
		L.RegVar("SystemNoticeFrame", get_SystemNoticeFrame, set_SystemNoticeFrame);
		L.RegVar("WingInfoUi", get_WingInfoUi, set_WingInfoUi);
		L.RegVar("SConfigs", get_SConfigs, set_SConfigs);
		L.RegVar("EquipPack", get_EquipPack, set_EquipPack);
		L.RegVar("ItemInfoGetUI", get_ItemInfoGetUI, set_ItemInfoGetUI);
		L.RegVar("DungeonRewardFrame", get_DungeonRewardFrame, set_DungeonRewardFrame);
		L.RegVar("CustomShopFrame", get_CustomShopFrame, set_CustomShopFrame);
		L.RegVar("AnswerUI", get_AnswerUI, set_AnswerUI);
		L.RegVar("FaceList", get_FaceList, set_FaceList);
		L.RegVar("ChatItemList", get_ChatItemList, set_ChatItemList);
		L.RegVar("PuzzleImage", get_PuzzleImage, set_PuzzleImage);
		L.RegVar("CleanDust", get_CleanDust, set_CleanDust);
		L.RegVar("LineConfim", get_LineConfim, set_LineConfim);
		L.RegVar("RechargeFrame", get_RechargeFrame, set_RechargeFrame);
		L.RegVar("PlayFrame", get_PlayFrame, set_PlayFrame);
		L.RegVar("TitleUI", get_TitleUI, set_TitleUI);
		L.RegVar("LevelUpTip", get_LevelUpTip, set_LevelUpTip);
		L.RegVar("MissionTip", get_MissionTip, set_MissionTip);
		L.RegVar("SevenDayReward", get_SevenDayReward, set_SevenDayReward);
		L.RegVar("StrongUI", get_StrongUI, set_StrongUI);
		L.RegVar("GuardUI", get_GuardUI, set_GuardUI);
		L.RegVar("RechargeActivityUI", get_RechargeActivityUI, set_RechargeActivityUI);
		L.RegVar("ShareFrame", get_ShareFrame, set_ShareFrame);
		L.RegVar("WorshipFrame", get_WorshipFrame, set_WorshipFrame);
		L.RegVar("OperationActivityFrame", get_OperationActivityFrame, set_OperationActivityFrame);
		L.RegVar("ModelDisplayFrame", get_ModelDisplayFrame, set_ModelDisplayFrame);
		L.RegVar("ShowItemsFrame", get_ShowItemsFrame, set_ShowItemsFrame);
		L.RegVar("FirstChargeFrame", get_FirstChargeFrame, set_FirstChargeFrame);
		L.RegVar("WingChargeFrame", get_WingChargeFrame, set_WingChargeFrame);
		L.RegVar("QuickBuyUi", get_QuickBuyUi, set_QuickBuyUi);
		L.RegVar("ArtifactUi", get_ArtifactUi, set_ArtifactUi);
		L.RegVar("MyArtifactUI", get_MyArtifactUI, set_MyArtifactUI);
		L.RegVar("BufferListUI", get_BufferListUI, set_BufferListUI);
		L.RegVar("MonsterSiegeUI", get_MonsterSiegeUI, set_MonsterSiegeUI);
		L.RegVar("GXRankingUI", get_GXRankingUI, set_GXRankingUI);
		L.RegVar("MishiResultUI", get_MishiResultUI, set_MishiResultUI);
		L.RegVar("BattryLevelUpUI", get_BattryLevelUpUI, set_BattryLevelUpUI);
		L.RegVar("MieShiTapUI", get_MieShiTapUI, set_MieShiTapUI);
		L.RegVar("ExchangeUI", get_ExchangeUI, set_ExchangeUI);
		L.RegVar("FuctionTipFrame", get_FuctionTipFrame, set_FuctionTipFrame);
		L.RegVar("MieShiSceneMapUI", get_MieShiSceneMapUI, set_MieShiSceneMapUI);
		L.RegVar("ChestInfoUI", get_ChestInfoUI, set_ChestInfoUI);
		L.RegVar("NameUI", get_NameUI, null);
		L.RegVar("PrefabPath", get_PrefabPath, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUIConfig(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				IControllerBase arg1 = (IControllerBase)ToLua.CheckObject(L, 2, typeof(IControllerBase));
				System.Type arg2 = (System.Type)ToLua.CheckObject(L, 3, typeof(System.Type));
				UIConfig obj = new UIConfig(arg0, arg1, arg2);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UIConfig.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IncReference(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UIConfig obj = (UIConfig)ToLua.CheckObject(L, 1, typeof(UIConfig));
			obj.IncReference();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DecReference(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UIConfig obj = (UIConfig)ToLua.CheckObject(L, 1, typeof(UIConfig));
			obj.DecReference();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Visible(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UIConfig obj = (UIConfig)ToLua.CheckObject(L, 1, typeof(UIConfig));
			bool o = obj.Visible();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CleanReferenceCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UIConfig obj = (UIConfig)ToLua.CheckObject(L, 1, typeof(UIConfig));
			obj.CleanReferenceCount();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			UIConfig.Reset();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CleanupControllers(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			UIConfig.CleanupControllers();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			UIConfig.Init();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int NewArgument(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UIConfig obj = (UIConfig)ToLua.CheckObject(L, 1, typeof(UIConfig));
			UIInitArguments o = obj.NewArgument();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetConfig(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			UIConfig o = UIConfig.GetConfig(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIConfig arg0 = (UIConfig)ToLua.ToObject(L, 1);
			UIConfig arg1 = (UIConfig)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TypeUI(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIConfig obj = (UIConfig)o;
			UIType ret = obj.TypeUI;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index TypeUI on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Loction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIConfig obj = (UIConfig)o;
			UnityEngine.Vector3 ret = obj.Loction;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Loction on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UiRecord(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIConfig obj = (UIConfig)o;
			DataTable.UIRecord ret = obj.UiRecord;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UiRecord on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SceneMapUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SceneMapUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MainUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MainUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackPackUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.BackPackUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AttriFrameUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.AttriFrameUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SelectEquipsUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SelectEquipsUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SelectRoleUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SelectRoleUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BlockLayer(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.BlockLayer);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SkillFrameUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SkillFrameUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SkillTipFrameUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SkillTipFrameUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MissionFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MissionFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DialogFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.DialogFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TeamFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.TeamFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MissionList(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MissionList);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MissionTrackList(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MissionTrackList);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OperationList(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.OperationList);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MessageBox(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MessageBox);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RewardFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.RewardFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EquipUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.EquipUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AchievementFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.AchievementFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ChatMainFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ChatMainFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AchievementTip(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.AchievementTip);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HandBook(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.HandBook);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FriendUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.FriendUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DungeonUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.DungeonUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ComposeUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ComposeUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AttributeUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.AttributeUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SettingUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SettingUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RankUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.RankUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PlayerInfoUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.PlayerInfoUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MailUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MailUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CharacterUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.CharacterUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DepotUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.DepotUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StoreUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.StoreUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StoreEquip(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.StoreEquip);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StoreFarm(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.StoreFarm);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ElfUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ElfUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WingUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.WingUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SailingUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SailingUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FarmUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.FarmUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ServerListUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ServerListUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MedalInfoUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MedalInfoUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AreanaUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.AreanaUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AreanaResult(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.AreanaResult);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ReliveUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ReliveUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WishingUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.WishingUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SmithyUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SmithyUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TradingUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.TradingUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DungeonResult(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.DungeonResult);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RecycleUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.RecycleUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BattleUnionUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.BattleUnionUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ForceUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ForceUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ItemInfoUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ItemInfoUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EquipComPareUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.EquipComPareUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EquipInfoUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.EquipInfoUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GainItemHintUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.GainItemHintUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ElfInfoUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ElfInfoUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BattleUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.BattleUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BattleResult(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.BattleResult);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AstrologyUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.AstrologyUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NewbieGuide(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.NewbieGuide);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ActivityUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ActivityUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ActivityRewardFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ActivityRewardFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BossRewardFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.BossRewardFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RebornUi(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.RebornUi);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OffLineExpFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.OffLineExpFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SystemNoticeFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SystemNoticeFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WingInfoUi(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.WingInfoUi);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SConfigs(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SConfigs);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EquipPack(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.EquipPack);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ItemInfoGetUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ItemInfoGetUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DungeonRewardFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.DungeonRewardFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CustomShopFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.CustomShopFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AnswerUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.AnswerUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FaceList(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.FaceList);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ChatItemList(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ChatItemList);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PuzzleImage(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.PuzzleImage);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CleanDust(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.CleanDust);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LineConfim(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.LineConfim);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RechargeFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.RechargeFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PlayFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.PlayFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TitleUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.TitleUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LevelUpTip(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.LevelUpTip);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MissionTip(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MissionTip);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SevenDayReward(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.SevenDayReward);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StrongUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.StrongUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GuardUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.GuardUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RechargeActivityUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.RechargeActivityUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ShareFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ShareFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WorshipFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.WorshipFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OperationActivityFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.OperationActivityFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ModelDisplayFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ModelDisplayFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ShowItemsFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ShowItemsFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FirstChargeFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.FirstChargeFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WingChargeFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.WingChargeFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QuickBuyUi(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.QuickBuyUi);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ArtifactUi(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ArtifactUi);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MyArtifactUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MyArtifactUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BufferListUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.BufferListUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MonsterSiegeUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MonsterSiegeUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GXRankingUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.GXRankingUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MishiResultUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MishiResultUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BattryLevelUpUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.BattryLevelUpUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MieShiTapUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MieShiTapUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExchangeUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ExchangeUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FuctionTipFrame(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.FuctionTipFrame);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MieShiSceneMapUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.MieShiSceneMapUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ChestInfoUI(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UIConfig.ChestInfoUI);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NameUI(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIConfig obj = (UIConfig)o;
			string ret = obj.NameUI;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index NameUI on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PrefabPath(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIConfig obj = (UIConfig)o;
			string ret = obj.PrefabPath;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index PrefabPath on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TypeUI(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIConfig obj = (UIConfig)o;
			UIType arg0 = (UIType)ToLua.CheckObject(L, 2, typeof(UIType));
			obj.TypeUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index TypeUI on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Loction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIConfig obj = (UIConfig)o;
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.Loction = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Loction on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_UiRecord(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIConfig obj = (UIConfig)o;
			DataTable.UIRecord arg0 = (DataTable.UIRecord)ToLua.CheckObject(L, 2, typeof(DataTable.UIRecord));
			obj.UiRecord = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UiRecord on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SceneMapUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SceneMapUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MainUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MainUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BackPackUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.BackPackUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AttriFrameUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.AttriFrameUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SelectEquipsUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SelectEquipsUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SelectRoleUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SelectRoleUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BlockLayer(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.BlockLayer = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SkillFrameUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SkillFrameUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SkillTipFrameUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SkillTipFrameUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MissionFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MissionFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_DialogFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.DialogFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TeamFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.TeamFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MissionList(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MissionList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MissionTrackList(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MissionTrackList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OperationList(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.OperationList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MessageBox(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MessageBox = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RewardFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.RewardFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_EquipUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.EquipUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AchievementFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.AchievementFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ChatMainFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ChatMainFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AchievementTip(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.AchievementTip = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_HandBook(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.HandBook = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_FriendUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.FriendUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_DungeonUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.DungeonUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ComposeUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ComposeUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AttributeUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.AttributeUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SettingUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SettingUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RankUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.RankUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_PlayerInfoUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.PlayerInfoUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MailUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MailUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CharacterUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.CharacterUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_DepotUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.DepotUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_StoreUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.StoreUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_StoreEquip(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.StoreEquip = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_StoreFarm(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.StoreFarm = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ElfUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ElfUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_WingUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.WingUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SailingUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SailingUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_FarmUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.FarmUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ServerListUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ServerListUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MedalInfoUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MedalInfoUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AreanaUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.AreanaUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AreanaResult(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.AreanaResult = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ReliveUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ReliveUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_WishingUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.WishingUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SmithyUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SmithyUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TradingUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.TradingUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_DungeonResult(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.DungeonResult = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RecycleUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.RecycleUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BattleUnionUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.BattleUnionUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ForceUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ForceUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ItemInfoUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ItemInfoUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_EquipComPareUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.EquipComPareUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_EquipInfoUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.EquipInfoUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GainItemHintUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.GainItemHintUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ElfInfoUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ElfInfoUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BattleUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.BattleUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BattleResult(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.BattleResult = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AstrologyUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.AstrologyUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_NewbieGuide(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.NewbieGuide = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ActivityUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ActivityUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ActivityRewardFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ActivityRewardFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BossRewardFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.BossRewardFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RebornUi(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.RebornUi = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OffLineExpFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.OffLineExpFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SystemNoticeFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SystemNoticeFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_WingInfoUi(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.WingInfoUi = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SConfigs(IntPtr L)
	{
		try
		{
			System.Collections.Generic.Dictionary<int,UIConfig> arg0 = (System.Collections.Generic.Dictionary<int,UIConfig>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<int,UIConfig>));
			UIConfig.SConfigs = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_EquipPack(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.EquipPack = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ItemInfoGetUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ItemInfoGetUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_DungeonRewardFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.DungeonRewardFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CustomShopFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.CustomShopFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AnswerUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.AnswerUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_FaceList(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.FaceList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ChatItemList(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ChatItemList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_PuzzleImage(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.PuzzleImage = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CleanDust(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.CleanDust = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LineConfim(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.LineConfim = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RechargeFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.RechargeFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_PlayFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.PlayFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TitleUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.TitleUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LevelUpTip(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.LevelUpTip = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MissionTip(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MissionTip = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SevenDayReward(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.SevenDayReward = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_StrongUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.StrongUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GuardUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.GuardUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RechargeActivityUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.RechargeActivityUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ShareFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ShareFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_WorshipFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.WorshipFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OperationActivityFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.OperationActivityFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ModelDisplayFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ModelDisplayFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ShowItemsFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ShowItemsFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_FirstChargeFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.FirstChargeFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_WingChargeFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.WingChargeFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_QuickBuyUi(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.QuickBuyUi = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ArtifactUi(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ArtifactUi = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MyArtifactUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MyArtifactUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BufferListUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.BufferListUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MonsterSiegeUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MonsterSiegeUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GXRankingUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.GXRankingUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MishiResultUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MishiResultUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BattryLevelUpUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.BattryLevelUpUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MieShiTapUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MieShiTapUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ExchangeUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ExchangeUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_FuctionTipFrame(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.FuctionTipFrame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MieShiSceneMapUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.MieShiSceneMapUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ChestInfoUI(IntPtr L)
	{
		try
		{
			UIConfig arg0 = (UIConfig)ToLua.CheckObject(L, 2, typeof(UIConfig));
			UIConfig.ChestInfoUI = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

