//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Chat9xTypeClient.proto
// Note: requires additional types generated from: CommonData.proto
// Note: requires additional types generated from: MessageData.proto
// Note: requires additional types generated from: ServerData.proto
namespace DataContract
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GMChat_RET_int32__")]
  public partial class __RPC_Chat_GMChat_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GMChat_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GMChat_ARG_string_commond__")]
  public partial class __RPC_Chat_GMChat_ARG_string_commond__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GMChat_ARG_string_commond__() {}
    

    private string _Commond = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Commond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Commond
    {
      get { return _Commond; }
      set { _Commond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ChatChatMessage_RET_int32__")]
  public partial class __RPC_Chat_ChatChatMessage_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ChatChatMessage_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ChatChatMessage_ARG_int32_chatType_ChatMessageContent_Content_uint64_characterId__")]
  public partial class __RPC_Chat_ChatChatMessage_ARG_int32_chatType_ChatMessageContent_Content_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ChatChatMessage_ARG_int32_chatType_ChatMessageContent_Content_uint64_characterId__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ChatNotify_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_ChatNotify_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ChatNotify_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SendHornMessage_RET_int32__")]
  public partial class __RPC_Chat_SendHornMessage_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SendHornMessage_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SendHornMessage_ARG_uint32_serverId_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_SendHornMessage_ARG_uint32_serverId_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SendHornMessage_ARG_uint32_serverId_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private uint _ServerId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SyncChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_SyncChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SyncChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_BroadcastWorldMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_BroadcastWorldMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_BroadcastWorldMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GetRecentcontacts_RET_PlayerHeadInfoMsgList__")]
  public partial class __RPC_Chat_GetRecentcontacts_RET_PlayerHeadInfoMsgList__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GetRecentcontacts_RET_PlayerHeadInfoMsgList__() {}
    

    private DataContract.PlayerHeadInfoMsgList _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.PlayerHeadInfoMsgList ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GetRecentcontacts_ARG_int32_placeholder__")]
  public partial class __RPC_Chat_GetRecentcontacts_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GetRecentcontacts_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_DeleteRecentcontacts_RET_int32__")]
  public partial class __RPC_Chat_DeleteRecentcontacts_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_DeleteRecentcontacts_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_DeleteRecentcontacts_ARG_uint64_characterId__")]
  public partial class __RPC_Chat_DeleteRecentcontacts_ARG_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_DeleteRecentcontacts_ARG_uint64_characterId__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_EnterChannel_RET_int32__")]
  public partial class __RPC_Chat_EnterChannel_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_EnterChannel_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_EnterChannel_ARG_uint64_channelId_string_password__")]
  public partial class __RPC_Chat_EnterChannel_ARG_uint64_channelId_string_password__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_EnterChannel_ARG_uint64_channelId_string_password__() {}
    

    private ulong _ChannelId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChannelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ChannelId
    {
      get { return _ChannelId; }
      set { _ChannelId = value; }
    }

    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_LeaveChannel_RET_int32__")]
  public partial class __RPC_Chat_LeaveChannel_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_LeaveChannel_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_LeaveChannel_ARG_uint64_channelId__")]
  public partial class __RPC_Chat_LeaveChannel_ARG_uint64_channelId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_LeaveChannel_ARG_uint64_channelId__() {}
    

    private ulong _ChannelId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChannelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ChannelId
    {
      get { return _ChannelId; }
      set { _ChannelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SyncToListCityChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_Content_string_ChannelName__")]
  public partial class __RPC_Chat_SyncToListCityChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_Content_string_ChannelName__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SyncToListCityChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_Content_string_ChannelName__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }

    private string _ChannelName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ChannelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ChannelName
    {
      get { return _ChannelName; }
      set { _ChannelName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}