//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Login9xTypeClient.proto
// Note: requires additional types generated from: CommonData.proto
// Note: requires additional types generated from: MessageData.proto
// Note: requires additional types generated from: ServerData.proto
namespace DataContract
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_PlayerLoginByUserNamePassword_RET_PlayerLoginData__")]
  public partial class __RPC_Login_PlayerLoginByUserNamePassword_RET_PlayerLoginData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_PlayerLoginByUserNamePassword_RET_PlayerLoginData__() {}
    

    private DataContract.PlayerLoginData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.PlayerLoginData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_PlayerLoginByUserNamePassword_ARG_string_username_string_password__")]
  public partial class __RPC_Login_PlayerLoginByUserNamePassword_ARG_string_username_string_password__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_PlayerLoginByUserNamePassword_ARG_string_username_string_password__() {}
    

    private string _Username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Username
    {
      get { return _Username; }
      set { _Username = value; }
    }

    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_PlayerLoginByThirdKey_RET_PlayerLoginData__")]
  public partial class __RPC_Login_PlayerLoginByThirdKey_RET_PlayerLoginData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_PlayerLoginByThirdKey_RET_PlayerLoginData__() {}
    

    private DataContract.PlayerLoginData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.PlayerLoginData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_PlayerLoginByThirdKey_ARG_string_platform_string_channel_string_userId_string_accessToken__")]
  public partial class __RPC_Login_PlayerLoginByThirdKey_ARG_string_platform_string_channel_string_userId_string_accessToken__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_PlayerLoginByThirdKey_ARG_string_platform_string_channel_string_userId_string_accessToken__() {}
    

    private string _Platform = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Platform
    {
      get { return _Platform; }
      set { _Platform = value; }
    }

    private string _Channel = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Channel
    {
      get { return _Channel; }
      set { _Channel = value; }
    }

    private string _UserId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"UserId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UserId
    {
      get { return _UserId; }
      set { _UserId = value; }
    }

    private string _AccessToken = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"AccessToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccessToken
    {
      get { return _AccessToken; }
      set { _AccessToken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_PlayerSelectServerId_RET_CharacterListLoginMsg__")]
  public partial class __RPC_Login_PlayerSelectServerId_RET_CharacterListLoginMsg__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_PlayerSelectServerId_RET_CharacterListLoginMsg__() {}
    

    private DataContract.CharacterListLoginMsg _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.CharacterListLoginMsg ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_PlayerSelectServerId_ARG_int32_serverId__")]
  public partial class __RPC_Login_PlayerSelectServerId_ARG_int32_serverId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_PlayerSelectServerId_ARG_int32_serverId__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_Kick_ARG_int32_type__")]
  public partial class __RPC_Login_Kick_ARG_int32_type__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_Kick_ARG_int32_type__() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_Logout_ARG_uint64_characterId__")]
  public partial class __RPC_Login_Logout_ARG_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_Logout_ARG_uint64_characterId__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_CreateCharacter_RET_CharacterListLoginMsg__")]
  public partial class __RPC_Login_CreateCharacter_RET_CharacterListLoginMsg__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_CreateCharacter_RET_CharacterListLoginMsg__() {}
    

    private DataContract.CharacterListLoginMsg _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.CharacterListLoginMsg ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_CreateCharacter_ARG_int32_serverId_int32_type_string_name__")]
  public partial class __RPC_Login_CreateCharacter_ARG_int32_serverId_int32_type_string_name__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_CreateCharacter_ARG_int32_serverId_int32_type_string_name__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_EnterGame_RET_EnterGameData__")]
  public partial class __RPC_Login_EnterGame_RET_EnterGameData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_EnterGame_RET_EnterGameData__() {}
    

    private DataContract.EnterGameData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.EnterGameData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_EnterGame_ARG_uint64_characterId__")]
  public partial class __RPC_Login_EnterGame_ARG_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_EnterGame_ARG_uint64_characterId__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_SyncTime_RET_uint64__")]
  public partial class __RPC_Login_SyncTime_RET_uint64__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_SyncTime_RET_uint64__() {}
    

    private ulong _ReturnValue = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_SyncTime_ARG_int32_placeholder__")]
  public partial class __RPC_Login_SyncTime_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_SyncTime_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_GetServerList_RET_ServerListData__")]
  public partial class __RPC_Login_GetServerList_RET_ServerListData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_GetServerList_RET_ServerListData__() {}
    

    private DataContract.ServerListData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ServerListData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_GetServerList_ARG_int32_placeholder__")]
  public partial class __RPC_Login_GetServerList_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_GetServerList_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_NotifyQueueIndex_ARG_int32_index__")]
  public partial class __RPC_Login_NotifyQueueIndex_ARG_int32_index__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_NotifyQueueIndex_ARG_int32_index__() {}
    

    private int _Index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_Discard0_ARG_PlayerLoginData_plData__")]
  public partial class __RPC_Login_Discard0_ARG_PlayerLoginData_plData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_Discard0_ARG_PlayerLoginData_plData__() {}
    

    private DataContract.PlayerLoginData _PlData = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PlData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.PlayerLoginData PlData
    {
      get { return _PlData; }
      set { _PlData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_ExitLogin_ARG_int32_placeholder__")]
  public partial class __RPC_Login_ExitLogin_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_ExitLogin_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_ExitSelectCharacter_RET_CharacterListLoginMsg__")]
  public partial class __RPC_Login_ExitSelectCharacter_RET_CharacterListLoginMsg__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_ExitSelectCharacter_RET_CharacterListLoginMsg__() {}
    

    private DataContract.CharacterListLoginMsg _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.CharacterListLoginMsg ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_ExitSelectCharacter_ARG_uint64_characterId__")]
  public partial class __RPC_Login_ExitSelectCharacter_ARG_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_ExitSelectCharacter_ARG_uint64_characterId__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_NotifyQueueSuccess_ARG_QueueSuccessData_data__")]
  public partial class __RPC_Login_NotifyQueueSuccess_ARG_QueueSuccessData_data__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_NotifyQueueSuccess_ARG_QueueSuccessData_data__() {}
    

    private DataContract.QueueSuccessData _Data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.QueueSuccessData Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_QueryServerTimezone_RET_int32__")]
  public partial class __RPC_Login_QueryServerTimezone_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_QueryServerTimezone_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_QueryServerTimezone_ARG_int32_placeholder__")]
  public partial class __RPC_Login_QueryServerTimezone_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_QueryServerTimezone_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_GateDisconnect_ARG_uint64_clientId_uint64_characterId__")]
  public partial class __RPC_Login_GateDisconnect_ARG_uint64_clientId_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_GateDisconnect_ARG_uint64_clientId_uint64_characterId__() {}
    

    private ulong _ClientId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ClientId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ClientId
    {
      get { return _ClientId; }
      set { _ClientId = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_ReConnet_RET_int32__")]
  public partial class __RPC_Login_ReConnet_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_ReConnet_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_ReConnet_ARG_uint64_clientId_uint64_characterId__")]
  public partial class __RPC_Login_ReConnet_ARG_uint64_clientId_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_ReConnet_ARG_uint64_clientId_uint64_characterId__() {}
    

    private ulong _ClientId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ClientId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ClientId
    {
      get { return _ClientId; }
      set { _ClientId = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_NotifyReConnet_ARG_int32_result__")]
  public partial class __RPC_Login_NotifyReConnet_ARG_int32_result__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_NotifyReConnet_ARG_int32_result__() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Login_SendDeviceUdid_ARG_string_deviceUdid__")]
  public partial class __RPC_Login_SendDeviceUdid_ARG_string_deviceUdid__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Login_SendDeviceUdid_ARG_string_deviceUdid__() {}
    

    private string _DeviceUdid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"DeviceUdid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DeviceUdid
    {
      get { return _DeviceUdid; }
      set { _DeviceUdid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}