//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Team9xTypeClient.proto
// Note: requires additional types generated from: CommonData.proto
// Note: requires additional types generated from: MessageData.proto
// Note: requires additional types generated from: ServerData.proto
namespace DataContract
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamMessage_RET_int32__")]
  public partial class __RPC_Team_TeamMessage_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamMessage_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamMessage_ARG_uint64_characterId_int32_type_uint64_teamId_uint64_otherId__")]
  public partial class __RPC_Team_TeamMessage_ARG_uint64_characterId_int32_type_uint64_teamId_uint64_otherId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamMessage_ARG_uint64_characterId_int32_type_uint64_teamId_uint64_otherId__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private ulong _TeamId = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TeamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TeamId
    {
      get { return _TeamId; }
      set { _TeamId = value; }
    }

    private ulong _OtherId = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OtherId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong OtherId
    {
      get { return _OtherId; }
      set { _OtherId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_NotifyTeamMessage_ARG_int32_type_uint64_teamId_uint64_characterId__")]
  public partial class __RPC_Team_NotifyTeamMessage_ARG_int32_type_uint64_teamId_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_NotifyTeamMessage_ARG_int32_type_uint64_teamId_uint64_characterId__() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private ulong _TeamId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TeamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TeamId
    {
      get { return _TeamId; }
      set { _TeamId = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyTeam_RET_TeamMsg__")]
  public partial class __RPC_Team_ApplyTeam_RET_TeamMsg__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyTeam_RET_TeamMsg__() {}
    

    private DataContract.TeamMsg _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.TeamMsg ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyTeam_ARG_uint64_characterId__")]
  public partial class __RPC_Team_ApplyTeam_ARG_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyTeam_ARG_uint64_characterId__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamChatMessage_RET_int32__")]
  public partial class __RPC_Team_TeamChatMessage_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamChatMessage_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamChatMessage_ARG_int32_chatType_ChatMessageContent_Content_uint64_characterId__")]
  public partial class __RPC_Team_TeamChatMessage_ARG_int32_chatType_ChatMessageContent_Content_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamChatMessage_ARG_int32_chatType_ChatMessageContent_Content_uint64_characterId__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamDungeonLineUp_RET_int32__")]
  public partial class __RPC_Team_TeamDungeonLineUp_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamDungeonLineUp_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamDungeonLineUp_ARG_int32_dungeonId__")]
  public partial class __RPC_Team_TeamDungeonLineUp_ARG_int32_dungeonId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamDungeonLineUp_ARG_int32_dungeonId__() {}
    

    private int _DungeonId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"DungeonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DungeonId
    {
      get { return _DungeonId; }
      set { _DungeonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_MatchingStart_RET_MatchingResult__")]
  public partial class __RPC_Team_MatchingStart_RET_MatchingResult__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_MatchingStart_RET_MatchingResult__() {}
    

    private DataContract.MatchingResult _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.MatchingResult ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_MatchingStart_ARG_int32_queueId__")]
  public partial class __RPC_Team_MatchingStart_ARG_int32_queueId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_MatchingStart_ARG_int32_queueId__() {}
    

    private int _QueueId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"QueueId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int QueueId
    {
      get { return _QueueId; }
      set { _QueueId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_MatchingCancel_RET_int32__")]
  public partial class __RPC_Team_MatchingCancel_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_MatchingCancel_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_MatchingCancel_ARG_int32_queueId__")]
  public partial class __RPC_Team_MatchingCancel_ARG_int32_queueId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_MatchingCancel_ARG_int32_queueId__() {}
    

    private int _QueueId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"QueueId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int QueueId
    {
      get { return _QueueId; }
      set { _QueueId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_MatchingSuccess_ARG_int32_queueId__")]
  public partial class __RPC_Team_MatchingSuccess_ARG_int32_queueId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_MatchingSuccess_ARG_int32_queueId__() {}
    

    private int _QueueId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"QueueId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int QueueId
    {
      get { return _QueueId; }
      set { _QueueId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_NotifyMatchingData_ARG_QueueInfo_queueInfo__")]
  public partial class __RPC_Team_NotifyMatchingData_ARG_QueueInfo_queueInfo__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_NotifyMatchingData_ARG_QueueInfo_queueInfo__() {}
    

    private DataContract.QueueInfo _QueueInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"QueueInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.QueueInfo QueueInfo
    {
      get { return _QueueInfo; }
      set { _QueueInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_MatchingBack_ARG_int32_result__")]
  public partial class __RPC_Team_MatchingBack_ARG_int32_result__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_MatchingBack_ARG_int32_result__() {}
    

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamServerMessage_ARG_int32_resultType_string_args__")]
  public partial class __RPC_Team_TeamServerMessage_ARG_int32_resultType_string_args__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamServerMessage_ARG_int32_resultType_string_args__() {}
    

    private int _ResultType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ResultType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ResultType
    {
      get { return _ResultType; }
      set { _ResultType = value; }
    }

    private string _Args = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Args
    {
      get { return _Args; }
      set { _Args = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyQueueData_RET_QueueInfo__")]
  public partial class __RPC_Team_ApplyQueueData_RET_QueueInfo__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyQueueData_RET_QueueInfo__() {}
    

    private DataContract.QueueInfo _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.QueueInfo ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyQueueData_ARG_int32_placeholder__")]
  public partial class __RPC_Team_ApplyQueueData_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyQueueData_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamEnterFuben_RET_Uint64Array__")]
  public partial class __RPC_Team_TeamEnterFuben_RET_Uint64Array__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamEnterFuben_RET_Uint64Array__() {}
    

    private DataContract.Uint64Array _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.Uint64Array ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamEnterFuben_ARG_int32_fubenId_int32_serverId__")]
  public partial class __RPC_Team_TeamEnterFuben_ARG_int32_fubenId_int32_serverId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamEnterFuben_ARG_int32_fubenId_int32_serverId__() {}
    

    private int _FubenId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"FubenId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int FubenId
    {
      get { return _FubenId; }
      set { _FubenId = value; }
    }

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_SyncTeamEnterFuben_ARG_int32_fubenId__")]
  public partial class __RPC_Team_SyncTeamEnterFuben_ARG_int32_fubenId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_SyncTeamEnterFuben_ARG_int32_fubenId__() {}
    

    private int _FubenId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"FubenId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int FubenId
    {
      get { return _FubenId; }
      set { _FubenId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ResultTeamEnterFuben_ARG_int32_fubenID_int32_isOk__")]
  public partial class __RPC_Team_ResultTeamEnterFuben_ARG_int32_fubenID_int32_isOk__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ResultTeamEnterFuben_ARG_int32_fubenID_int32_isOk__() {}
    

    private int _FubenID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"FubenID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int FubenID
    {
      get { return _FubenID; }
      set { _FubenID = value; }
    }

    private int _IsOk = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IsOk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int IsOk
    {
      get { return _IsOk; }
      set { _IsOk = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_GMTeam_RET_int32__")]
  public partial class __RPC_Team_GMTeam_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_GMTeam_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_GMTeam_ARG_string_commond__")]
  public partial class __RPC_Team_GMTeam_ARG_string_commond__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_GMTeam_ARG_string_commond__() {}
    

    private string _Commond = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Commond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Commond
    {
      get { return _Commond; }
      set { _Commond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_MemberWantInvite_ARG_int32_type_string_memberName_string_toName_uint64_toId__")]
  public partial class __RPC_Team_MemberWantInvite_ARG_int32_type_string_memberName_string_toName_uint64_toId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_MemberWantInvite_ARG_int32_type_string_memberName_string_toName_uint64_toId__() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private string _MemberName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"MemberName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MemberName
    {
      get { return _MemberName; }
      set { _MemberName = value; }
    }

    private string _ToName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ToName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ToName
    {
      get { return _ToName; }
      set { _ToName = value; }
    }

    private ulong _ToId = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ToId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ToId
    {
      get { return _ToId; }
      set { _ToId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_SyncAllianceMessage_ARG_int32_type_string_name1_int32_allianceId_string_name2__")]
  public partial class __RPC_Team_SyncAllianceMessage_ARG_int32_type_string_name1_int32_allianceId_string_name2__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_SyncAllianceMessage_ARG_int32_type_string_name1_int32_allianceId_string_name2__() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private string _Name1 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name1
    {
      get { return _Name1; }
      set { _Name1 = value; }
    }

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }

    private string _Name2 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Name2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name2
    {
      get { return _Name2; }
      set { _Name2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceData_RET_AllianceData__")]
  public partial class __RPC_Team_ApplyAllianceData_RET_AllianceData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceData_RET_AllianceData__() {}
    

    private DataContract.AllianceData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceData_ARG_int32_allianceId__")]
  public partial class __RPC_Team_ApplyAllianceData_ARG_int32_allianceId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceData_ARG_int32_allianceId__() {}
    

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceDataByServerId_RET_AllianceData__")]
  public partial class __RPC_Team_ApplyAllianceDataByServerId_RET_AllianceData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceDataByServerId_RET_AllianceData__() {}
    

    private DataContract.AllianceData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceDataByServerId_ARG_int32_serverId_int32_type__")]
  public partial class __RPC_Team_ApplyAllianceDataByServerId_ARG_int32_serverId_int32_type__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceDataByServerId_ARG_int32_serverId_int32_type__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ChangeAllianceNotice_RET_int32__")]
  public partial class __RPC_Team_ChangeAllianceNotice_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ChangeAllianceNotice_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ChangeAllianceNotice_ARG_int32_allianceId_string_Content__")]
  public partial class __RPC_Team_ChangeAllianceNotice_ARG_int32_allianceId_string_Content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ChangeAllianceNotice_ARG_int32_allianceId_string_Content__() {}
    

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }

    private string _Content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_GetServerAlliance_RET_AllianceSimpleDataList__")]
  public partial class __RPC_Team_GetServerAlliance_RET_AllianceSimpleDataList__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_GetServerAlliance_RET_AllianceSimpleDataList__() {}
    

    private DataContract.AllianceSimpleDataList _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceSimpleDataList ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_GetServerAlliance_ARG_int32_serverId__")]
  public partial class __RPC_Team_GetServerAlliance_ARG_int32_serverId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_GetServerAlliance_ARG_int32_serverId__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ChangeJurisdiction_RET_int32__")]
  public partial class __RPC_Team_ChangeJurisdiction_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ChangeJurisdiction_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ChangeJurisdiction_ARG_int32_allianceId_uint64_guid_int32_type__")]
  public partial class __RPC_Team_ChangeJurisdiction_ARG_int32_allianceId_uint64_guid_int32_type__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ChangeJurisdiction_ARG_int32_allianceId_uint64_guid_int32_type__() {}
    

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }

    private ulong _Guid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ChangeAllianceAutoJoin_RET_int32__")]
  public partial class __RPC_Team_ChangeAllianceAutoJoin_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ChangeAllianceAutoJoin_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ChangeAllianceAutoJoin_ARG_int32_allianceId_int32_value__")]
  public partial class __RPC_Team_ChangeAllianceAutoJoin_ARG_int32_allianceId_int32_value__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ChangeAllianceAutoJoin_ARG_int32_allianceId_int32_value__() {}
    

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }

    private int _Value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Value
    {
      get { return _Value; }
      set { _Value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_AllianceAgreeApplyList_RET_int32__")]
  public partial class __RPC_Team_AllianceAgreeApplyList_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_AllianceAgreeApplyList_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_AllianceAgreeApplyList_ARG_int32_allianceId_int32_type_Uint64Array_guids__")]
  public partial class __RPC_Team_AllianceAgreeApplyList_ARG_int32_allianceId_int32_type_Uint64Array_guids__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_AllianceAgreeApplyList_ARG_int32_allianceId_int32_type_Uint64Array_guids__() {}
    

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private DataContract.Uint64Array _Guids = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Guids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.Uint64Array Guids
    {
      get { return _Guids; }
      set { _Guids = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_SendMatchingMessage_ARG_int32_NowCount__")]
  public partial class __RPC_Team_SendMatchingMessage_ARG_int32_NowCount__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_SendMatchingMessage_ARG_int32_NowCount__() {}
    

    private int _NowCount = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"NowCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int NowCount
    {
      get { return _NowCount; }
      set { _NowCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_TeamSyncAllianceMessage_ARG_int32_type_string_name1_int32_allianceId_string_name2__")]
  public partial class __RPC_Team_TeamSyncAllianceMessage_ARG_int32_type_string_name1_int32_allianceId_string_name2__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_TeamSyncAllianceMessage_ARG_int32_type_string_name1_int32_allianceId_string_name2__() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private string _Name1 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name1
    {
      get { return _Name1; }
      set { _Name1 = value; }
    }

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }

    private string _Name2 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Name2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name2
    {
      get { return _Name2; }
      set { _Name2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ChangeAllianceData_ARG_int32_type_int32_param1_int32_param2__")]
  public partial class __RPC_Team_ChangeAllianceData_ARG_int32_type_int32_param1_int32_param2__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ChangeAllianceData_ARG_int32_type_int32_param1_int32_param2__() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private int _Param1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Param1
    {
      get { return _Param1; }
      set { _Param1 = value; }
    }

    private int _Param2 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Param2
    {
      get { return _Param2; }
      set { _Param2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceMissionData_RET_AllianceMissionData__")]
  public partial class __RPC_Team_ApplyAllianceMissionData_RET_AllianceMissionData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceMissionData_RET_AllianceMissionData__() {}
    

    private DataContract.AllianceMissionData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceMissionData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceMissionData_ARG_int32_allianceId__")]
  public partial class __RPC_Team_ApplyAllianceMissionData_ARG_int32_allianceId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceMissionData_ARG_int32_allianceId__() {}
    

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_UpgradeAllianceLevel_RET_int32__")]
  public partial class __RPC_Team_UpgradeAllianceLevel_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_UpgradeAllianceLevel_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_UpgradeAllianceLevel_ARG_int32_allianceId__")]
  public partial class __RPC_Team_UpgradeAllianceLevel_ARG_int32_allianceId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_UpgradeAllianceLevel_ARG_int32_allianceId__() {}
    

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceEnjoyList_RET_AllianceEnjoyData__")]
  public partial class __RPC_Team_ApplyAllianceEnjoyList_RET_AllianceEnjoyData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceEnjoyList_RET_AllianceEnjoyData__() {}
    

    private DataContract.AllianceEnjoyData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceEnjoyData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceEnjoyList_ARG_int32_allianceId__")]
  public partial class __RPC_Team_ApplyAllianceEnjoyList_ARG_int32_allianceId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceEnjoyList_ARG_int32_allianceId__() {}
    

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceDonationList_RET_AllianceDonationData__")]
  public partial class __RPC_Team_ApplyAllianceDonationList_RET_AllianceDonationData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceDonationList_RET_AllianceDonationData__() {}
    

    private DataContract.AllianceDonationData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceDonationData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceDonationList_ARG_int32_allianceId__")]
  public partial class __RPC_Team_ApplyAllianceDonationList_ARG_int32_allianceId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceDonationList_ARG_int32_allianceId__() {}
    

    private int _AllianceId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AllianceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AllianceId
    {
      get { return _AllianceId; }
      set { _AllianceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_SendGroupMessage_ARG_StringArray_contents__")]
  public partial class __RPC_Team_SendGroupMessage_ARG_StringArray_contents__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_SendGroupMessage_ARG_StringArray_contents__() {}
    

    private DataContract.StringArray _Contents = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Contents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.StringArray Contents
    {
      get { return _Contents; }
      set { _Contents = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_NotifyQueueMessage_ARG_TeamCharacterMessage_tcm__")]
  public partial class __RPC_Team_NotifyQueueMessage_ARG_TeamCharacterMessage_tcm__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_NotifyQueueMessage_ARG_TeamCharacterMessage_tcm__() {}
    

    private DataContract.TeamCharacterMessage _Tcm = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Tcm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.TeamCharacterMessage Tcm
    {
      get { return _Tcm; }
      set { _Tcm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_NotifyQueueResult_ARG_uint64_characterId_int32_result__")]
  public partial class __RPC_Team_NotifyQueueResult_ARG_uint64_characterId_int32_result__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_NotifyQueueResult_ARG_uint64_characterId_int32_result__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private int _Result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceWarOccupantData_RET_AllianceWarOccupantData__")]
  public partial class __RPC_Team_ApplyAllianceWarOccupantData_RET_AllianceWarOccupantData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceWarOccupantData_RET_AllianceWarOccupantData__() {}
    

    private DataContract.AllianceWarOccupantData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceWarOccupantData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceWarOccupantData_ARG_int32_serverId__")]
  public partial class __RPC_Team_ApplyAllianceWarOccupantData_ARG_int32_serverId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceWarOccupantData_ARG_int32_serverId__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_NotifyAllianceWarOccupantData_ARG_AllianceWarOccupantData_data__")]
  public partial class __RPC_Team_NotifyAllianceWarOccupantData_ARG_AllianceWarOccupantData_data__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_NotifyAllianceWarOccupantData_ARG_AllianceWarOccupantData_data__() {}
    

    private DataContract.AllianceWarOccupantData _Data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceWarOccupantData Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceWarChallengerData_RET_AllianceWarChallengerData__")]
  public partial class __RPC_Team_ApplyAllianceWarChallengerData_RET_AllianceWarChallengerData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceWarChallengerData_RET_AllianceWarChallengerData__() {}
    

    private DataContract.AllianceWarChallengerData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceWarChallengerData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceWarChallengerData_ARG_int32_serverId__")]
  public partial class __RPC_Team_ApplyAllianceWarChallengerData_ARG_int32_serverId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceWarChallengerData_ARG_int32_serverId__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_NotifyAllianceWarChallengerData_ARG_AllianceWarChallengerData_data__")]
  public partial class __RPC_Team_NotifyAllianceWarChallengerData_ARG_AllianceWarChallengerData_data__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_NotifyAllianceWarChallengerData_ARG_AllianceWarChallengerData_data__() {}
    

    private DataContract.AllianceWarChallengerData _Data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceWarChallengerData Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceWarData_RET_AllianceWarData__")]
  public partial class __RPC_Team_ApplyAllianceWarData_RET_AllianceWarData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceWarData_RET_AllianceWarData__() {}
    

    private DataContract.AllianceWarData _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AllianceWarData ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_ApplyAllianceWarData_ARG_int32_serverId__")]
  public partial class __RPC_Team_ApplyAllianceWarData_ARG_int32_serverId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_ApplyAllianceWarData_ARG_int32_serverId__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_BidAllianceWar_RET_int32__")]
  public partial class __RPC_Team_BidAllianceWar_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_BidAllianceWar_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_BidAllianceWar_ARG_int32_price__")]
  public partial class __RPC_Team_BidAllianceWar_ARG_int32_price__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_BidAllianceWar_ARG_int32_price__() {}
    

    private int _Price = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Price
    {
      get { return _Price; }
      set { _Price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_EnterAllianceWar_RET_int32__")]
  public partial class __RPC_Team_EnterAllianceWar_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_EnterAllianceWar_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_EnterAllianceWar_ARG_int32_placeholder__")]
  public partial class __RPC_Team_EnterAllianceWar_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_EnterAllianceWar_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_SyncAllianceChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Team_SyncAllianceChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_SyncAllianceChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_CSSelectItemAuction_RET_AuctionItemList__")]
  public partial class __RPC_Team_CSSelectItemAuction_RET_AuctionItemList__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_CSSelectItemAuction_RET_AuctionItemList__() {}
    

    private DataContract.AuctionItemList _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.AuctionItemList ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Team_CSSelectItemAuction_ARG_int32_serverId_int32_type__")]
  public partial class __RPC_Team_CSSelectItemAuction_ARG_int32_serverId_int32_type__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Team_CSSelectItemAuction_ARG_int32_serverId_int32_type__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}